---

- name: Install acmetool
  package:
    name: 'acmetool'
    state: present
  tags:
    - installation
    - acmetool


# Todo: Reconsider best practice
#- name: Remove acmetool snippet for nginx from package installation
#  file:
#    path: '/etc/nginx/snippets/acmetool.conf'
#    state: absent
#  tags:
#    - installation
#    - configuration
#    - acmetool


- name: Create directory for acmetool response file
  file:
    name: '/var/lib/acme/conf'
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'
  tags:
    - installation
    - acmetool


- name: Copy acmetool response file
  template:
    src: 'files/response-file.yml.j2'
    dest: '/var/lib/acme/conf/responses'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  tags:
    - configuration
    - acmetool
# Todo: with_first_found?


- name: Perform acmetool quickstart
  command: acmetool quickstart --expert
  args:
    creates: '/var/lib/acme/conf/target'
  tags:
    - configuration
    - operation
    - acmetool


- name: Copy hook to enable acmetool to restart services
  copy:
    src: 'files/restart'
    dest: '/etc/acme/hooks/'
    owner: root
    group: root
    mode: 'u=rx,g=rx,o=rx'
  tags:
    - configuration
    - acmetool


- name: Reload systemd and enable acmetool timer unit
  systemd:
    name: 'acmetool.timer'
    daemon_reload: yes
    enabled: yes
    state: started
  tags:
    - operation
    - acmetool
